"""
Token Metrics Display Component
Expandable detailed view showing token usage and cost
"""

import streamlit as st
from src.utils.token_tracker import TokenTracker


def display_token_metrics():
    """
    Display token usage and cost metrics in an expandable view
    Option B: Compact summary with expandable details
    """
    # Initialize tracker
    TokenTracker.initialize()

    # Get current usage
    usage = TokenTracker.get_usage()

    total_cost = usage['total_cost']
    total_tokens = usage['total_tokens']

    # Custom CSS for the token metrics card
    st.markdown("""
    <style>
        .token-metrics-card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border-radius: 12px;
            padding: 1rem;
            margin: 1rem 0;
            color: white;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .token-cost-main {
            font-size: 1.8rem;
            font-weight: bold;
            text-align: center;
            margin-bottom: 0.5rem;
        }
        .token-label {
            font-size: 0.9rem;
            text-align: center;
            opacity: 0.9;
        }
        .token-detail-row {
            display: flex;
            justify-content: space-between;
            padding: 0.5rem 0;
            border-bottom: 1px solid rgba(255,255,255,0.2);
        }
        .token-detail-label {
            font-weight: 500;
        }
        .token-detail-value {
            font-weight: bold;
        }
        .agent-breakdown-item {
            background-color: rgba(255,255,255,0.1);
            border-radius: 6px;
            padding: 0.5rem;
            margin: 0.5rem 0;
        }
    </style>
    """, unsafe_allow_html=True)

    # Main compact card
    st.markdown(f"""
    <div class="token-metrics-card">
        <div class="token-cost-main">💰 {TokenTracker.format_cost(total_cost)}</div>
        <div class="token-label">Session Cost</div>
    </div>
    """, unsafe_allow_html=True)

    # Expandable details
    with st.expander("📊 View Token Details", expanded=False):
        # Overall metrics
        st.markdown("### 📈 Overall Usage")

        st.metric(
            label="📥 Input Tokens",
            value=TokenTracker.format_tokens(usage['input_tokens']),
            help="Total tokens sent to the model"
        )

        st.metric(
            label="📤 Output Tokens",
            value=TokenTracker.format_tokens(usage['output_tokens']),
            help="Total tokens generated by the model"
        )

        st.metric(
            label="🔢 Total Tokens",
            value=TokenTracker.format_tokens(total_tokens),
            help="Sum of input and output tokens"
        )

        st.divider()

        # Agent breakdown
        agent_breakdown = TokenTracker.get_agent_breakdown()

        if agent_breakdown:
            st.markdown("### 🤖 Agent Breakdown")

            for agent_data in agent_breakdown:
                agent_name = agent_data['agent']
                agent_cost = agent_data['cost']
                agent_tokens = agent_data['total_tokens']
                agent_calls = agent_data['calls']

                # Calculate percentage of total
                if total_tokens > 0:
                    percentage = (agent_tokens / total_tokens) * 100
                else:
                    percentage = 0

                with st.container():
                    col1, col2, col3 = st.columns([2, 1, 1])

                    with col1:
                        st.markdown(f"**{agent_name}**")
                        st.progress(percentage / 100)

                    with col2:
                        st.markdown(f"**{TokenTracker.format_tokens(agent_tokens)}** tokens")
                        st.caption(f"{percentage:.1f}% of total")

                    with col3:
                        st.markdown(f"**{TokenTracker.format_cost(agent_cost)}**")
                        st.caption(f"{agent_calls} call{'s' if agent_calls != 1 else ''}")

        else:
            st.info("No agent calls yet. Token usage will appear here once agents start analyzing your data.")

        st.divider()

        # Reset button
        col1, col2 = st.columns([1, 1])

        with col1:
            if st.button("🔄 Reset Token Tracking", help="Clear all token usage data for this session", use_container_width=True):
                TokenTracker.reset()
                st.success("✅ Token tracking reset!")
                st.rerun()

        with col2:
            # Show total requests count
            request_count = len(usage['requests'])
            st.info(f"📊 **{request_count}** total API call{'s' if request_count != 1 else ''}")


def display_mini_token_badge():
    """
    Display a minimal token cost badge (alternative compact view)
    """
    TokenTracker.initialize()
    usage = TokenTracker.get_usage()

    total_cost = usage['total_cost']

    # Color based on cost
    if total_cost < 0.01:
        color = "#28a745"  # Green
    elif total_cost < 0.05:
        color = "#ffc107"  # Yellow
    else:
        color = "#dc3545"  # Red

    st.markdown(f"""
    <div style="
        background-color: {color};
        color: white;
        padding: 0.5rem 1rem;
        border-radius: 20px;
        text-align: center;
        font-weight: bold;
        font-size: 1.1rem;
        margin: 0.5rem 0;
    ">
        💰 Session Cost: {TokenTracker.format_cost(total_cost)}
    </div>
    """, unsafe_allow_html=True)
